name: Prepare for deploy on push to master branch

on:
  push:
    branches:
      - master

jobs:
  predeploy-on-push:
    name: Predeploy on push to master branch

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store/v3
          key: cache-pnpm-${{ hashFiles('./package-lock.json') }}
          restore-keys: cache-pnpm-

      - name: Install dependencies
        run: corepack enable && pnpm i

      - name: Build project
        run: pnpm build
        env:
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.PATH_TO_DIST }}
          branch: gh-pages
